/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 6.6.2
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QFrame>
#include <QtWidgets/QLCDNumber>
#include <QtWidgets/QLabel>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QProgressBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QTextBrowser>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralwidget;
    QComboBox *comboBox;
    QCheckBox *checkBox;
    QPushButton *b1;
    QPushButton *b2;
    QPushButton *b4;
    QPushButton *b3;
    QPushButton *b6;
    QPushButton *b8;
    QPushButton *b5;
    QPushButton *b7;
    QPushButton *b10;
    QPushButton *b12;
    QPushButton *b9;
    QPushButton *b13;
    QPushButton *b11;
    QPushButton *b15;
    QPushButton *b18;
    QPushButton *b20;
    QPushButton *b17;
    QPushButton *b22;
    QPushButton *b21;
    QPushButton *b19;
    QPushButton *b24;
    QPushButton *b14;
    QPushButton *b16;
    QPushButton *b23;
    QPushButton *b25;
    QPushButton *b30;
    QPushButton *b34;
    QPushButton *b32;
    QPushButton *b28;
    QPushButton *b27;
    QPushButton *b36;
    QPushButton *b26;
    QPushButton *b35;
    QPushButton *b31;
    QPushButton *b29;
    QPushButton *b33;
    QPushButton *b41;
    QPushButton *b46;
    QPushButton *b44;
    QPushButton *b40;
    QPushButton *b37;
    QPushButton *b38;
    QPushButton *b42;
    QPushButton *b39;
    QPushButton *b43;
    QPushButton *b45;
    QPushButton *CapsLock;
    QPushButton *Shift;
    QPushButton *Space;
    QFrame *line;
    QFrame *line_2;
    QFrame *line_4;
    QLabel *label;
    QFrame *line_5;
    QFrame *line_6;
    QFrame *line_7;
    QTextBrowser *textBrowser;
    QFrame *line_8;
    QPushButton *OpenFileButton;
    QPushButton *StartButton;
    QLabel *label_2;
    QLCDNumber *h;
    QLCDNumber *ms;
    QLCDNumber *s;
    QLCDNumber *m;
    QLabel *label_3;
    QLabel *label_4;
    QLabel *label_5;
    QLabel *label_6;
    QLabel *chars_per_second;
    QProgressBar *progressBar;
    QPushButton *b0;
    QFrame *line_3;
    QLabel *label_7;
    QLabel *accuracy;
    QLabel *Result;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName("MainWindow");
        MainWindow->resize(1600, 900);
        MainWindow->setMinimumSize(QSize(1600, 900));
        MainWindow->setMaximumSize(QSize(1600, 900));
        centralwidget = new QWidget(MainWindow);
        centralwidget->setObjectName("centralwidget");
        comboBox = new QComboBox(centralwidget);
        comboBox->addItem(QString());
        comboBox->addItem(QString());
        comboBox->addItem(QString());
        comboBox->addItem(QString());
        comboBox->addItem(QString());
        comboBox->addItem(QString());
        comboBox->setObjectName("comboBox");
        comboBox->setGeometry(QRect(0, 0, 181, 31));
        QFont font;
        font.setPointSize(14);
        comboBox->setFont(font);
        comboBox->setFocusPolicy(Qt::NoFocus);
        checkBox = new QCheckBox(centralwidget);
        checkBox->setObjectName("checkBox");
        checkBox->setGeometry(QRect(460, 840, 181, 41));
        checkBox->setFocusPolicy(Qt::NoFocus);
        b1 = new QPushButton(centralwidget);
        b1->setObjectName("b1");
        b1->setGeometry(QRect(460, 640, 41, 41));
        b1->setFocusPolicy(Qt::NoFocus);
        b2 = new QPushButton(centralwidget);
        b2->setObjectName("b2");
        b2->setGeometry(QRect(510, 640, 41, 41));
        b2->setFocusPolicy(Qt::NoFocus);
        b4 = new QPushButton(centralwidget);
        b4->setObjectName("b4");
        b4->setGeometry(QRect(610, 640, 41, 41));
        b4->setFocusPolicy(Qt::NoFocus);
        b3 = new QPushButton(centralwidget);
        b3->setObjectName("b3");
        b3->setGeometry(QRect(560, 640, 41, 41));
        b3->setFocusPolicy(Qt::NoFocus);
        b6 = new QPushButton(centralwidget);
        b6->setObjectName("b6");
        b6->setGeometry(QRect(710, 640, 41, 41));
        b6->setFocusPolicy(Qt::NoFocus);
        b8 = new QPushButton(centralwidget);
        b8->setObjectName("b8");
        b8->setGeometry(QRect(810, 640, 41, 41));
        b8->setFocusPolicy(Qt::NoFocus);
        b5 = new QPushButton(centralwidget);
        b5->setObjectName("b5");
        b5->setGeometry(QRect(660, 640, 41, 41));
        b5->setFocusPolicy(Qt::NoFocus);
        b7 = new QPushButton(centralwidget);
        b7->setObjectName("b7");
        b7->setGeometry(QRect(760, 640, 41, 41));
        b7->setFocusPolicy(Qt::NoFocus);
        b10 = new QPushButton(centralwidget);
        b10->setObjectName("b10");
        b10->setGeometry(QRect(910, 640, 41, 41));
        b10->setFocusPolicy(Qt::NoFocus);
        b12 = new QPushButton(centralwidget);
        b12->setObjectName("b12");
        b12->setGeometry(QRect(1010, 640, 41, 41));
        b12->setFocusPolicy(Qt::NoFocus);
        b9 = new QPushButton(centralwidget);
        b9->setObjectName("b9");
        b9->setGeometry(QRect(860, 640, 41, 41));
        b9->setFocusPolicy(Qt::NoFocus);
        b13 = new QPushButton(centralwidget);
        b13->setObjectName("b13");
        b13->setGeometry(QRect(1060, 640, 41, 41));
        b13->setFocusPolicy(Qt::NoFocus);
        b11 = new QPushButton(centralwidget);
        b11->setObjectName("b11");
        b11->setGeometry(QRect(960, 640, 41, 41));
        b11->setFocusPolicy(Qt::NoFocus);
        b15 = new QPushButton(centralwidget);
        b15->setObjectName("b15");
        b15->setGeometry(QRect(580, 690, 41, 41));
        b15->setFocusPolicy(Qt::NoFocus);
        b18 = new QPushButton(centralwidget);
        b18->setObjectName("b18");
        b18->setGeometry(QRect(730, 690, 41, 41));
        b18->setFocusPolicy(Qt::NoFocus);
        b20 = new QPushButton(centralwidget);
        b20->setObjectName("b20");
        b20->setGeometry(QRect(830, 690, 41, 41));
        b20->setFocusPolicy(Qt::NoFocus);
        b17 = new QPushButton(centralwidget);
        b17->setObjectName("b17");
        b17->setGeometry(QRect(680, 690, 41, 41));
        b17->setFocusPolicy(Qt::NoFocus);
        b22 = new QPushButton(centralwidget);
        b22->setObjectName("b22");
        b22->setGeometry(QRect(930, 690, 41, 41));
        b22->setFocusPolicy(Qt::NoFocus);
        b21 = new QPushButton(centralwidget);
        b21->setObjectName("b21");
        b21->setGeometry(QRect(880, 690, 41, 41));
        b21->setFocusPolicy(Qt::NoFocus);
        b19 = new QPushButton(centralwidget);
        b19->setObjectName("b19");
        b19->setGeometry(QRect(780, 690, 41, 41));
        b19->setFocusPolicy(Qt::NoFocus);
        b24 = new QPushButton(centralwidget);
        b24->setObjectName("b24");
        b24->setGeometry(QRect(1030, 690, 41, 41));
        b24->setFocusPolicy(Qt::NoFocus);
        b14 = new QPushButton(centralwidget);
        b14->setObjectName("b14");
        b14->setGeometry(QRect(530, 690, 41, 41));
        b14->setFocusPolicy(Qt::NoFocus);
        b16 = new QPushButton(centralwidget);
        b16->setObjectName("b16");
        b16->setGeometry(QRect(630, 690, 41, 41));
        b16->setFocusPolicy(Qt::NoFocus);
        b23 = new QPushButton(centralwidget);
        b23->setObjectName("b23");
        b23->setGeometry(QRect(980, 690, 41, 41));
        b23->setFocusPolicy(Qt::NoFocus);
        b25 = new QPushButton(centralwidget);
        b25->setObjectName("b25");
        b25->setGeometry(QRect(1080, 690, 41, 41));
        b25->setFocusPolicy(Qt::NoFocus);
        b30 = new QPushButton(centralwidget);
        b30->setObjectName("b30");
        b30->setGeometry(QRect(750, 740, 41, 41));
        b30->setFocusPolicy(Qt::NoFocus);
        b34 = new QPushButton(centralwidget);
        b34->setObjectName("b34");
        b34->setGeometry(QRect(950, 740, 41, 41));
        b34->setFocusPolicy(Qt::NoFocus);
        b32 = new QPushButton(centralwidget);
        b32->setObjectName("b32");
        b32->setGeometry(QRect(850, 740, 41, 41));
        b32->setFocusPolicy(Qt::NoFocus);
        b28 = new QPushButton(centralwidget);
        b28->setObjectName("b28");
        b28->setGeometry(QRect(650, 740, 41, 41));
        b28->setFocusPolicy(Qt::NoFocus);
        b27 = new QPushButton(centralwidget);
        b27->setObjectName("b27");
        b27->setGeometry(QRect(600, 740, 41, 41));
        b27->setFocusPolicy(Qt::NoFocus);
        b36 = new QPushButton(centralwidget);
        b36->setObjectName("b36");
        b36->setGeometry(QRect(1050, 740, 41, 41));
        b36->setFocusPolicy(Qt::NoFocus);
        b26 = new QPushButton(centralwidget);
        b26->setObjectName("b26");
        b26->setGeometry(QRect(550, 740, 41, 41));
        b26->setFocusPolicy(Qt::NoFocus);
        b35 = new QPushButton(centralwidget);
        b35->setObjectName("b35");
        b35->setGeometry(QRect(1000, 740, 41, 41));
        b35->setFocusPolicy(Qt::NoFocus);
        b31 = new QPushButton(centralwidget);
        b31->setObjectName("b31");
        b31->setGeometry(QRect(800, 740, 41, 41));
        b31->setFocusPolicy(Qt::NoFocus);
        b29 = new QPushButton(centralwidget);
        b29->setObjectName("b29");
        b29->setGeometry(QRect(700, 740, 41, 41));
        b29->setFocusPolicy(Qt::NoFocus);
        b33 = new QPushButton(centralwidget);
        b33->setObjectName("b33");
        b33->setGeometry(QRect(900, 740, 41, 41));
        b33->setFocusPolicy(Qt::NoFocus);
        b41 = new QPushButton(centralwidget);
        b41->setObjectName("b41");
        b41->setGeometry(QRect(770, 790, 41, 41));
        b41->setFocusPolicy(Qt::NoFocus);
        b46 = new QPushButton(centralwidget);
        b46->setObjectName("b46");
        b46->setGeometry(QRect(1020, 790, 41, 41));
        b46->setFocusPolicy(Qt::NoFocus);
        b44 = new QPushButton(centralwidget);
        b44->setObjectName("b44");
        b44->setGeometry(QRect(920, 790, 41, 41));
        b44->setFocusPolicy(Qt::NoFocus);
        b40 = new QPushButton(centralwidget);
        b40->setObjectName("b40");
        b40->setGeometry(QRect(720, 790, 41, 41));
        b40->setFocusPolicy(Qt::NoFocus);
        b37 = new QPushButton(centralwidget);
        b37->setObjectName("b37");
        b37->setGeometry(QRect(570, 790, 41, 41));
        b37->setFocusPolicy(Qt::NoFocus);
        b38 = new QPushButton(centralwidget);
        b38->setObjectName("b38");
        b38->setGeometry(QRect(620, 790, 41, 41));
        b38->setFocusPolicy(Qt::NoFocus);
        b42 = new QPushButton(centralwidget);
        b42->setObjectName("b42");
        b42->setGeometry(QRect(820, 790, 41, 41));
        b42->setFocusPolicy(Qt::NoFocus);
        b39 = new QPushButton(centralwidget);
        b39->setObjectName("b39");
        b39->setGeometry(QRect(670, 790, 41, 41));
        b39->setFocusPolicy(Qt::NoFocus);
        b43 = new QPushButton(centralwidget);
        b43->setObjectName("b43");
        b43->setGeometry(QRect(870, 790, 41, 41));
        b43->setFocusPolicy(Qt::NoFocus);
        b45 = new QPushButton(centralwidget);
        b45->setObjectName("b45");
        b45->setGeometry(QRect(970, 790, 41, 41));
        b45->setFocusPolicy(Qt::NoFocus);
        CapsLock = new QPushButton(centralwidget);
        CapsLock->setObjectName("CapsLock");
        CapsLock->setGeometry(QRect(460, 740, 81, 41));
        CapsLock->setFocusPolicy(Qt::NoFocus);
        Shift = new QPushButton(centralwidget);
        Shift->setObjectName("Shift");
        Shift->setGeometry(QRect(460, 790, 101, 41));
        Shift->setFocusPolicy(Qt::NoFocus);
        Space = new QPushButton(centralwidget);
        Space->setObjectName("Space");
        Space->setGeometry(QRect(670, 840, 240, 41));
        Space->setFocusPolicy(Qt::NoFocus);
        line = new QFrame(centralwidget);
        line->setObjectName("line");
        line->setGeometry(QRect(-10, 630, 1610, 3));
        line->setFocusPolicy(Qt::NoFocus);
        line->setFrameShape(QFrame::HLine);
        line->setFrameShadow(QFrame::Sunken);
        line_2 = new QFrame(centralwidget);
        line_2->setObjectName("line_2");
        line_2->setGeometry(QRect(1130, 630, 3, 270));
        line_2->setFocusPolicy(Qt::NoFocus);
        line_2->setFrameShape(QFrame::VLine);
        line_2->setFrameShadow(QFrame::Sunken);
        line_4 = new QFrame(centralwidget);
        line_4->setObjectName("line_4");
        line_4->setGeometry(QRect(-10, 730, 3, 61));
        line_4->setFocusPolicy(Qt::NoFocus);
        line_4->setFrameShape(QFrame::VLine);
        line_4->setFrameShadow(QFrame::Sunken);
        label = new QLabel(centralwidget);
        label->setObjectName("label");
        label->setGeometry(QRect(0, 50, 171, 181));
        QFont font1;
        font1.setPointSize(80);
        label->setFont(font1);
        label->setFocusPolicy(Qt::NoFocus);
        label->setStyleSheet(QString::fromUtf8("color:rgb(0, 255, 0)"));
        label->setAlignment(Qt::AlignCenter);
        line_5 = new QFrame(centralwidget);
        line_5->setObjectName("line_5");
        line_5->setGeometry(QRect(0, 40, 180, 3));
        line_5->setFocusPolicy(Qt::NoFocus);
        line_5->setFrameShape(QFrame::HLine);
        line_5->setFrameShadow(QFrame::Sunken);
        line_6 = new QFrame(centralwidget);
        line_6->setObjectName("line_6");
        line_6->setGeometry(QRect(180, 40, 3, 200));
        line_6->setFocusPolicy(Qt::NoFocus);
        line_6->setFrameShape(QFrame::VLine);
        line_6->setFrameShadow(QFrame::Sunken);
        line_7 = new QFrame(centralwidget);
        line_7->setObjectName("line_7");
        line_7->setGeometry(QRect(0, 240, 180, 3));
        line_7->setFocusPolicy(Qt::NoFocus);
        line_7->setFrameShape(QFrame::HLine);
        line_7->setFrameShadow(QFrame::Sunken);
        textBrowser = new QTextBrowser(centralwidget);
        textBrowser->setObjectName("textBrowser");
        textBrowser->setGeometry(QRect(200, 40, 1401, 201));
        textBrowser->setFont(font1);
        textBrowser->setFocusPolicy(Qt::NoFocus);
        line_8 = new QFrame(centralwidget);
        line_8->setObjectName("line_8");
        line_8->setGeometry(QRect(450, 630, 3, 270));
        line_8->setFocusPolicy(Qt::NoFocus);
        line_8->setFrameShape(QFrame::VLine);
        line_8->setFrameShadow(QFrame::Sunken);
        OpenFileButton = new QPushButton(centralwidget);
        OpenFileButton->setObjectName("OpenFileButton");
        OpenFileButton->setGeometry(QRect(200, 0, 1391, 31));
        OpenFileButton->setFocusPolicy(Qt::NoFocus);
        StartButton = new QPushButton(centralwidget);
        StartButton->setObjectName("StartButton");
        StartButton->setGeometry(QRect(0, 250, 180, 51));
        StartButton->setFocusPolicy(Qt::NoFocus);
        label_2 = new QLabel(centralwidget);
        label_2->setObjectName("label_2");
        label_2->setGeometry(QRect(1140, 640, 451, 141));
        label_2->setFont(font1);
        label_2->setAlignment(Qt::AlignCenter);
        h = new QLCDNumber(centralwidget);
        h->setObjectName("h");
        h->setGeometry(QRect(1140, 780, 90, 101));
        h->setDigitCount(2);
        ms = new QLCDNumber(centralwidget);
        ms->setObjectName("ms");
        ms->setGeometry(QRect(1500, 780, 90, 101));
        ms->setDigitCount(3);
        s = new QLCDNumber(centralwidget);
        s->setObjectName("s");
        s->setGeometry(QRect(1380, 780, 90, 101));
        s->setDigitCount(2);
        m = new QLCDNumber(centralwidget);
        m->setObjectName("m");
        m->setGeometry(QRect(1260, 780, 90, 101));
        m->setDigitCount(2);
        label_3 = new QLabel(centralwidget);
        label_3->setObjectName("label_3");
        label_3->setGeometry(QRect(1230, 780, 31, 101));
        QFont font2;
        font2.setPointSize(38);
        font2.setBold(true);
        label_3->setFont(font2);
        label_3->setAlignment(Qt::AlignCenter);
        label_4 = new QLabel(centralwidget);
        label_4->setObjectName("label_4");
        label_4->setGeometry(QRect(1350, 780, 31, 101));
        label_4->setFont(font2);
        label_4->setAlignment(Qt::AlignCenter);
        label_5 = new QLabel(centralwidget);
        label_5->setObjectName("label_5");
        label_5->setGeometry(QRect(1470, 780, 31, 101));
        label_5->setFont(font2);
        label_5->setAlignment(Qt::AlignCenter);
        label_6 = new QLabel(centralwidget);
        label_6->setObjectName("label_6");
        label_6->setGeometry(QRect(5, 639, 441, 41));
        QFont font3;
        font3.setPointSize(24);
        label_6->setFont(font3);
        label_6->setAlignment(Qt::AlignCenter);
        chars_per_second = new QLabel(centralwidget);
        chars_per_second->setObjectName("chars_per_second");
        chars_per_second->setGeometry(QRect(0, 690, 440, 50));
        QFont font4;
        font4.setPointSize(26);
        chars_per_second->setFont(font4);
        chars_per_second->setAlignment(Qt::AlignCenter);
        progressBar = new QProgressBar(centralwidget);
        progressBar->setObjectName("progressBar");
        progressBar->setGeometry(QRect(200, 250, 1391, 51));
        QFont font5;
        font5.setPointSize(17);
        progressBar->setFont(font5);
        progressBar->setValue(0);
        b0 = new QPushButton(centralwidget);
        b0->setObjectName("b0");
        b0->setEnabled(false);
        b0->setGeometry(QRect(460, 690, 61, 41));
        b0->setFocusPolicy(Qt::NoFocus);
        b0->setFlat(true);
        line_3 = new QFrame(centralwidget);
        line_3->setObjectName("line_3");
        line_3->setGeometry(QRect(0, 760, 450, 3));
        line_3->setFrameShape(QFrame::HLine);
        line_3->setFrameShadow(QFrame::Sunken);
        label_7 = new QLabel(centralwidget);
        label_7->setObjectName("label_7");
        label_7->setGeometry(QRect(0, 760, 441, 41));
        label_7->setFont(font3);
        label_7->setAlignment(Qt::AlignCenter);
        accuracy = new QLabel(centralwidget);
        accuracy->setObjectName("accuracy");
        accuracy->setGeometry(QRect(0, 830, 440, 50));
        accuracy->setFont(font4);
        accuracy->setAlignment(Qt::AlignCenter);
        Result = new QLabel(centralwidget);
        Result->setObjectName("Result");
        Result->setGeometry(QRect(0, 310, 1591, 311));
        Result->setAlignment(Qt::AlignCenter);
        MainWindow->setCentralWidget(centralwidget);

        retranslateUi(MainWindow);

        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QCoreApplication::translate("MainWindow", "MainWindow", nullptr));
        comboBox->setItemText(0, QCoreApplication::translate("MainWindow", "Belarusian", nullptr));
        comboBox->setItemText(1, QCoreApplication::translate("MainWindow", "Hebrew", nullptr));
        comboBox->setItemText(2, QCoreApplication::translate("MainWindow", "Deutch", nullptr));
        comboBox->setItemText(3, QCoreApplication::translate("MainWindow", "Arabic", nullptr));
        comboBox->setItemText(4, QCoreApplication::translate("MainWindow", "Chinese", nullptr));
        comboBox->setItemText(5, QCoreApplication::translate("MainWindow", "French", nullptr));

        checkBox->setText(QCoreApplication::translate("MainWindow", "Show useless buttons", nullptr));
        b1->setText(QCoreApplication::translate("MainWindow", "\320\201", nullptr));
        b2->setText(QCoreApplication::translate("MainWindow", "1", nullptr));
        b4->setText(QCoreApplication::translate("MainWindow", "3", nullptr));
        b3->setText(QCoreApplication::translate("MainWindow", "2", nullptr));
        b6->setText(QCoreApplication::translate("MainWindow", "5", nullptr));
        b8->setText(QCoreApplication::translate("MainWindow", "7", nullptr));
        b5->setText(QCoreApplication::translate("MainWindow", "4", nullptr));
        b7->setText(QCoreApplication::translate("MainWindow", "6", nullptr));
        b10->setText(QCoreApplication::translate("MainWindow", "9", nullptr));
        b12->setText(QCoreApplication::translate("MainWindow", "-", nullptr));
        b9->setText(QCoreApplication::translate("MainWindow", "8", nullptr));
        b13->setText(QCoreApplication::translate("MainWindow", "=", nullptr));
        b11->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        b15->setText(QCoreApplication::translate("MainWindow", "\321\206", nullptr));
        b18->setText(QCoreApplication::translate("MainWindow", "\320\265", nullptr));
        b20->setText(QCoreApplication::translate("MainWindow", "\320\263", nullptr));
        b17->setText(QCoreApplication::translate("MainWindow", "\320\272", nullptr));
        b22->setText(QCoreApplication::translate("MainWindow", "\321\236", nullptr));
        b21->setText(QCoreApplication::translate("MainWindow", "\321\210", nullptr));
        b19->setText(QCoreApplication::translate("MainWindow", "\320\275", nullptr));
        b24->setText(QCoreApplication::translate("MainWindow", "\321\205", nullptr));
        b14->setText(QCoreApplication::translate("MainWindow", "\320\271", nullptr));
        b16->setText(QCoreApplication::translate("MainWindow", "\321\203", nullptr));
        b23->setText(QCoreApplication::translate("MainWindow", "\320\267", nullptr));
        b25->setText(QCoreApplication::translate("MainWindow", "'", nullptr));
        b30->setText(QCoreApplication::translate("MainWindow", "\320\277", nullptr));
        b34->setText(QCoreApplication::translate("MainWindow", "\320\264", nullptr));
        b32->setText(QCoreApplication::translate("MainWindow", "\320\276", nullptr));
        b28->setText(QCoreApplication::translate("MainWindow", "\320\262", nullptr));
        b27->setText(QCoreApplication::translate("MainWindow", "\321\213", nullptr));
        b36->setText(QCoreApplication::translate("MainWindow", "\321\215", nullptr));
        b26->setText(QCoreApplication::translate("MainWindow", "\321\204", nullptr));
        b35->setText(QCoreApplication::translate("MainWindow", "\320\266", nullptr));
        b31->setText(QCoreApplication::translate("MainWindow", "\321\200", nullptr));
        b29->setText(QCoreApplication::translate("MainWindow", "\320\260", nullptr));
        b33->setText(QCoreApplication::translate("MainWindow", "\320\273", nullptr));
        b41->setText(QCoreApplication::translate("MainWindow", "\321\226", nullptr));
        b46->setText(QCoreApplication::translate("MainWindow", ".", nullptr));
        b44->setText(QCoreApplication::translate("MainWindow", "b", nullptr));
        b40->setText(QCoreApplication::translate("MainWindow", "\320\274", nullptr));
        b37->setText(QCoreApplication::translate("MainWindow", "\321\217", nullptr));
        b38->setText(QCoreApplication::translate("MainWindow", "\321\207", nullptr));
        b42->setText(QCoreApplication::translate("MainWindow", "\321\202", nullptr));
        b39->setText(QCoreApplication::translate("MainWindow", "\321\201", nullptr));
        b43->setText(QCoreApplication::translate("MainWindow", "\321\214", nullptr));
        b45->setText(QCoreApplication::translate("MainWindow", "\321\216", nullptr));
        CapsLock->setText(QCoreApplication::translate("MainWindow", "Caps Lock", nullptr));
        Shift->setText(QCoreApplication::translate("MainWindow", "Shift", nullptr));
        Space->setText(QCoreApplication::translate("MainWindow", "Space", nullptr));
        label->setText(QString());
        OpenFileButton->setText(QCoreApplication::translate("MainWindow", "Open task file", nullptr));
        StartButton->setText(QCoreApplication::translate("MainWindow", "Start", nullptr));
        label_2->setText(QCoreApplication::translate("MainWindow", "\342\217\262\360\237\221\250\360\237\217\277\342\200\215\360\237\246\275", nullptr));
        label_3->setText(QCoreApplication::translate("MainWindow", ":", nullptr));
        label_4->setText(QCoreApplication::translate("MainWindow", ":", nullptr));
        label_5->setText(QCoreApplication::translate("MainWindow", ":", nullptr));
        label_6->setText(QCoreApplication::translate("MainWindow", "Chars / second", nullptr));
        chars_per_second->setText(QString());
        b0->setText(QString());
        label_7->setText(QCoreApplication::translate("MainWindow", "Accuracy", nullptr));
        accuracy->setText(QString());
        Result->setText(QString());
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
